---
- name: install the nginx server
  apt:
    name: nginx
    state: latest
    update_cache: true
  notify: restart nginx
  
- name: import handlers
  import_tasks: ../handlers/main.yml

- name: force the handler
  meta: flush_handlers