---
- name: uninstall nginx
  apt:
    name: nginx
    autoclean: true
    autoremove: true
    purge: true
    state: absent

- name: run the shell command to see if nginx is gone
  shell: echo hello world
  register: foo

- name: print out the output of the shell command
  debug:
    msg: "{{ foo['stdout'] }}"